In [1]:
import pandas as pd
df=pd.read_csv('ad.csv')

In [2]:
df.head()

,session_id,DateTime,user_id,product,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,gender,age_level,user_depth,city_development_index,var_1,is_click
0,140690,2017-07-02 00:00,858557,C,359520,13787,4,NaN,10.0,Female,4.0,3.0,3.0,0,0
1,333291,2017-07-02 00:00,243253,C,105960,11085,5,NaN,8.0,Female,2.0,2.0,NaN,0,0
2,129781,2017-07-02 00:00,243253,C,359520,13787,4,NaN,8.0,Female,2.0,2.0,NaN,0,0
3,464848,2017-07-02 00:00,1097446,I,359520,13787,3,NaN,3.0,Male,3.0,3.0,2.0,1,0
4,90569,2017-07-02 00:01,663656,C,405490,60305,3,NaN,2.0,Male,2.0,3.0,2.0,1,0

In [3]:
df.describe()

,session_id,user_id,campaign_id,webpage_id,product_category_1,product_category_2,user_group_id,age_level,user_depth,city_development_index,var_1,is_click
count,463291.000000,4.632910e+05,463291.000000,463291.000000,463291.000000,97437.000000,445048.000000,445048.000000,445048.000000,338162.000000,463291.000000,463291.000000
mean,285544.090725,5.460497e+05,308474.540069,29685.878994,3.072427,162753.345105,3.477396,2.782266,2.878415,2.557121,0.422169,0.067627
std,168577.345887,3.294625e+05,126517.101294,21542.053106,1.304233,78743.742720,2.412889,1.069701,0.400130,0.921345,0.493906,0.251105
min,2.000000,4.000000e+00,82320.000000,1734.000000,1.000000,18595.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,137856.500000,2.578550e+05,118601.000000,13787.000000,2.000000,82527.000000,2.000000,2.000000,3.000000,2.000000,0.000000,0.000000
50%,285429.000000,5.318010e+05,359520.000000,13787.000000,3.000000,146115.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
75%,435535.500000,8.278490e+05,405490.000000,53587.000000,4.000000,254132.000000,4.000000,3.000000,3.000000,3.000000,1.000000,0.000000
max,595812.000000,1.141729e+06,414149.000000,60305.000000,5.000000,450184.000000,12.000000,6.000000,3.000000,4.000000,1.000000,1.000000

In [4]:
df.shape

(463291, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463291 entries, 0 to 463290
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   session_id              463291 non-null  int64
 1   DateTime                463291 non-null  object
 2   user_id                 463291 non-null  int64
 3   product                 463291 non-null  object
 4   campaign_id             463291 non-null  int64
 5   webpage_id              463291 non-null  int64
 6   product_category_1      463291 non-null  int64
 7   product_category_2      97437 non-null   float64
 8   user_group_id           445048 non-null  float64
 9   gender                  445048 non-null  object
 10  age_level               445048 non-null  float64
 11  user_depth              445048 non-null  float64
 12  city_development_index  338162 non-null  float64
 13  var_1                   463291 non-null  int64
 14  is_click                463291 non-null  int64
dtypes: float64(5), int64(7), object(3)
memory usage: 53.0+ MB

In [7]:
#data cleaning

In [8]:
#missing values treatment
df.isnull().sum()

session_id                     0
DateTime                       0
user_id                        0
product                        0
campaign_id                    0
webpage_id                     0
product_category_1             0
product_category_2        365854
user_group_id              18243
gender                     18243
age_level                  18243
user_depth                 18243
city_development_index    125129
var_1                          0
is_click                       0
dtype: int64

In [9]:
df.drop('product_category_2',axis=1,inplace=True)

In [47]:
df['city_development_index'].fillna(df['city_development_index'].median())

0         3.0
1         2.0
2         2.0
3         2.0
4         2.0
         ...
463286    2.0
463287    2.0
463288    2.0
463289    2.0
463290    4.0
Name: city_development_index, Length: 463291, dtype: float64

In [46]:
for col in ['user_group_id', 'gender', 'age_level', 'user_depth']:
    df[col].fillna(df[col].mode()[0])

In [14]:
df.isnull().sum()

session_id                0
DateTime                  0
user_id                   0
product                   0
campaign_id               0
webpage_id                0
product_category_1        0
user_group_id             0
gender                    0
age_level                 0
user_depth                0
city_development_index    0
var_1                     0
is_click                  0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [28]:
df['DateTime']=pd.to_datetime(df['DateTime'])

In [29]:
df['date']=df['DateTime'].dt.date

In [30]:
df['hour']=df['DateTime'].dt.hour

In [41]:
df['day_of_week'] = df['DateTime'].dt.day_name()

In [18]:
#EDA

In [24]:
df['is_click'].value_counts()
df['is_click'].value_counts(normalize=True)
# Only around 6% users clicked ads ie 6 out 0f 100 users

is_click
0    0.932373
1    0.067627
Name: proportion, dtype: float64

In [25]:
df.groupby('gender')['is_click'].mean()

gender
Female    0.064445
Male      0.068026
Name: is_click, dtype: float64

In [26]:
df.groupby('age_level')['is_click'].mean()

age_level
0.0    0.084967
1.0    0.074803
2.0    0.070919
3.0    0.065058
4.0    0.058723
5.0    0.074153
6.0    0.082276
Name: is_click, dtype: float64

In [34]:
df.groupby('hour')['is_click'].mean()

hour
0     0.068493
1     0.074608
2     0.052732
3     0.062237
4     0.057005
5     0.067027
6     0.072822
7     0.073978
8     0.070271
9     0.070101
10    0.067776
11    0.069543
12    0.068585
13    0.066420
14    0.065304
15    0.063929
16    0.067221
17    0.066347
18    0.066230
19    0.066691
20    0.066352
21    0.069529
22    0.066510
23    0.063736
Name: is_click, dtype: float64

In [36]:
df.groupby('product_category_1')['is_click'].mean()

product_category_1
1    0.071554
2    0.061720
3    0.083524
4    0.058932
5    0.059121
Name: is_click, dtype: float64

In [42]:
from sqlalchemy import engine
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Prafulsql4266@localhost/ad_click")

df.to_sql('ad_click_project', con=engine, if_exists='replace', index=False)

463291